version: '3.9'

networks:
  default:
    external: true
    name: cic

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cic_ussd
    volumes:
      - cic-ussd-pg:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - cic-ussd-redis:/data
    ports:
        - '6379:6379'
    healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
        interval: 10s
        timeout: 5s
        retries: 5
  cic-ussd:
    image: cic-ussd:latest
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/cic_ussd
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    command: npm run start

volumes:
  cic-ussd-pg:
    driver: local
  cic-ussd-redis:
    driver: local